[build-system]
requires = [
    "setuptools>=58.0.0",
    "setuptools_scm>=3.4.3",
    "pyqt-distutils>=0.7.3",
    "wheel>=0.37.0",
    "dulwich",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 120
select = [
    "E", "F", "W", "C90", "I", "UP", "C4",
    "RSE",
    "TCH",
    "PTH",

    "PLC",
    "PLC0208",  # iterating over set is also not deterministic, so we shouldn't do that!

    "PLE",
    "PLR0402", "PLR1701", "PLR1711", "PLR1722", "PLR0206",
    "PLR0133", "PLR0124",
]

# Version to target for generated code.
target-version = "py311"

[tool.ruff.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 25.
# Defaults to 10, but we're being very flexible right now
max-complexity = 25

[tool.ruff.flake8-type-checking]
runtime-evaluated-base-classes = ["randovania.bitpacking.json_dataclass.JsonDataclass"]
