[build-system]
requires = [
    "setuptools>=58.0.0",
    "setuptools_scm>=3.4.3",
    "pyqt-distutils>=0.7.3",
    "wheel>=0.37.0",
    "dulwich",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 120
select = ["E", "F", "W", "C90", "I", "UP", "C4"]

# Version to target for generated code.
target-version = "py311"

[tool.ruff.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 25.
# Defaults to 10, but we're being very flexible right now
max-complexity = 25