version: "3.3"

networks:
  web:
    external: true

services:
  randovania:
    image: "randovania/server:${VERSION}"
    volumes:
      - "${DATA_PATH}:/data"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PATH_PREFIX}.rule=Host(`${DOMAIN}`) && PathPrefix(`/${PATH_PREFIX}`)"
      - "traefik.http.routers.${PATH_PREFIX}.entrypoints=websecure"
      - "traefik.http.routers.${PATH_PREFIX}.tls.certresolver=myresolver"
      - "traefik.http.routers.${PATH_PREFIX}.middlewares=${PATH_PREFIX}_stripprefix"
      - "traefik.http.middlewares.${PATH_PREFIX}_stripprefix.stripprefix.prefixes=/${PATH_PREFIX}"
      - "traefik.http.services.${PATH_PREFIX}.loadbalancer.server.port=5000"

    networks:
      - web
    restart: always

  sqlite-web:
    image: "coleifer/sqlite-web"
    restart: always
    volumes:
      - "${DATA_PATH}:/data"
    command:
      - sqlite_web
      - "-H"
      - "0.0.0.0"
      - "-u"
      - "/sqlite-web/${PATH_PREFIX}"
      - "-x"
      - data.db

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sqlite_web_staging.rule=Host(`${DOMAIN}`) && PathPrefix(`/sqlite-web/${PATH_PREFIX}`)"
      - "traefik.http.routers.sqlite_web_staging.entrypoints=websecure"
      - "traefik.http.routers.sqlite_web_staging.tls.certresolver=myresolver"
      - "traefik.http.routers.sqlite_web_staging.middlewares=dashboard-auth@file"
      - "traefik.http.services.sqlite_web_staging.loadbalancer.server.port=8080"

    networks:
      - web

  bot:
    image: "randovania/server:${VERSION}"
    volumes:
      - "${DATA_PATH}:/data"

    command: --configuration /data/configuration.json server bot
    restart: always
