name: Daily Test Generate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  report:
    runs-on: self-hosted
    container:
      image: randovania/server:edge

    steps:
      - name: Bulk Generate
        run:
          ./tools/bulk_generate_for_discord.sh
        env:
          WEBHOOK_URL: ${{ secrets.DREAD_DEV_TALK_WEBHOOK }}

  notify_failure:
    runs-on: ubuntu-latest
    needs: report
    if: ${{ failure() }}
    steps:
      - name: Alert Failure
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DREAD_DEV_TALK_WEBHOOK }}
          nodetail: true
          title: Bulk Generation failed!
          description: |
            [Daily Bulk Generation failed for `${{ github.ref_name }}`](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})